### ISSUE TITLE
Incompatibility with Node 0.12

### ISSUE THREAD

**Issue by Naktibalda** [pagerinc/jackrabbit#14]
[package.json](https://github.com/pagerinc/jackrabbit/blob/master/package.json#L25) states that this library is compatible with `node": ">= 0.10.x"`.

Actually it doesn't work on Node 0.12, because [exchange.js](https://github.com/pagerinc/jackrabbit/blob/v4.6.5/lib/exchange.js#L214) uses arrow function.
```js
var timeout = setTimeout(() => {
```

Error:
```sh
$ node -v
v0.12.18
$ node src/worker.js
/.../node_modules/@pager/jackrabbit/lib/exchange.js:214
      var timeout = setTimeout(() => {
                                ^
SyntaxError: Unexpected token )
```

**Comment by cilindrox** [comment]
Thanks for reporting this @Naktibalda !
