### ISSUE TITLE
Update readme for require statements..,.

### ISSUE THREAD

**Issue by tracker1** [pagerinc/jackrabbit#167]
Replace `require('jackrabbit');` with `require('@pager/jackrabbit');`

**Comment by tracker1** [comment]
Would also suggest adding the following npm keywords...

* rabbitmq
* rpc
* drpc
* distributed-rpc

So that it's more discoverable when searching for an rpc rabbit library in npm...  If I get time and remember tomorrow will create a PR for this.

**Comment by cilindrox** [comment]
Thanks for this @tracker1
