### ISSUE TITLE
Help with rpcClient/rpcServer

### ISSUE THREAD

**Issue by tracker1** [pagerinc/jackrabbit#181]
I'm getting the message on the rpcServer side, but the reply() doesn't wind up back on the requesting side....  It looks like the appropriate queues are being created, and the work/rpc queue of 'rir' is being ack'd but no response is coming through on the client side.

![image](https://user-images.githubusercontent.com/444316/72394202-96e81880-36f2-11ea-97bf-8351217f1db2.png)

Server:
```js
  const { server, queue } = config.mq;
  const rabbit = jackrabbit(server);
  const exchange = rabbit.default();
  exchange.rpcServer(queue, handleRequest({ listenerNumber, log, config }));
  log.debug({ message: `listener ${listenerNumber} Started`, listenerNumber, pid: process.pid });
```

Server handle-request
```js
export default ({ listenerNumber, log, config }) => (request, reply) => {
  const ctx = { listenerNumber, config, log, request };
  handleRequest(ctx)
    .catch(handleError(ctx) /* Error handler not hit */)
    .then(response => {
      log.response({ response });
      reply(response);
    });
};
```

Client:
```js
import jackrabbit from '@pager/jackrabbit';
// Will add a context method for doing an RPC request to the worker

export default (ctx, next) => {
  if (!ctx.app.rpc) {
    const { server, queue } = ctx.app.config.mq;
    const rabbit = jackrabbit(server);
    const exchange = rabbit.default();

    ctx.app.rpc = request =>
      new Promise((resolve, reject) => {
        try {
          exchange.rpcClient(queue, request, resolve);
        } catch (error) {
          reject(error);
        }
      });
  }
  ctx.rpc = ctx.app.rpc;
  return next();
};
```

I'm plugging it into my koa app...  the resolve never hits, I tried replacing it with console.log ... Is the `Excl` (exclusive) feature setting an issue?  Sorry, I'm not very familiar with AMQP or rabbit, I used the upstream library a few years ago for this, but no longer have access to that code, and really just started on what I'm currently working on.

**Comment by tracker1** [comment]
looks like examples/6-rpc works, but 7 does not...

**Comment by ryanhallcs** [comment]
Hey @tracker1 - good call. The examples need lots of updates - looks like the calls weren't aligned at all. I walked through it a bit and found:

- 6 worked due to the manual setup of a simple queue/publish rpc workflow
- 7 had a bug in the call structure: https://github.com/pagerinc/jackrabbit/blob/master/lib/exchange.js#L69 has and 4 params, and the callback for the client was sent in an options position https://github.com/pagerinc/jackrabbit/blob/master/examples/7-timeout-rpc/client.js#L6

Also confirm that in testing, the client is not publishing prior to the server finishing the rpc setup

**Comment by tracker1** [comment]
Thanks... will probably update once the update is published to npm.

I'm setting up the client as follows, and the server should definitely be up, I'm fronting RPC requests via an API interface to make it easier for other systems to call into.

```js
async function createRpcClient({server, method}) {
  const rabbit = jackrabbit(server);
  const exchange = rabbit.default();
  const rpc = exchange.queue({ name: method, prefetch: 1, durable: false });
  await new Promise((resolve, reject) => rpc.on('connected', resolve).on('error', reject));

  return request =>
    new Promise((resolve, reject) => {
      try {
        exchange.publish(request, { key: method, reply: resolve });
      } catch (error) {
        reject(error);
      }
    });
}
```

**Comment by tracker1** [comment]
oh, should change the connected event to ready.

**Comment by tracker1** [comment]
@ryanhallcs any chance of an npm publish for recent changes?

**Comment by cilindrox** [comment]
v5.0.0 seems to be out - thanks @ryanhallcs and @tracker1 !

**Comment by ryanhallcs** [comment]
@tracker1 were you able to sort out the issues?

**Comment by tracker1** [comment]
@ryanhallcs yeah... sorry, will close this now.
