### ISSUE TITLE
What version of RabbitMQ is supported by this Library?

### ISSUE THREAD

**Issue by TheScree** [pagerinc/jackrabbit#383]
Didn't see any mention in the Readme.rd for this information. Want to make sure that before I adopt a library that its going to support the latest version of RabbitMQ.

**Comment by jugaltheshah** [comment]
Hi @TheScree - this library depends on [amqplib](https://www.npmjs.com/package/amqplib). As amqplib `0.6.0` supports AMQP protocol version `0-9-1`, this library should support any version of RabbitMQ that supports AMQP `0-9-1`, which [according to this doc](https://www.rabbitmq.com/protocols.html), looks like all present versions. As RabbitMQ implements AMQP `1.0.0` only as a plugin with no mention of deprecating support for `0-9-1`, this library should work for the foreseeable future.
