### ISSUE TITLE
Creating a Reply Queue for Exchanges is Not Optional

### ISSUE THREAD

**Issue by Akamaozu** [pagerinc/jackrabbit#69]
In Hunter Loftis' version, we pass `noReply` when creating an exchange to prevent a reply queue from being automagically created.

https://github.com/hunterloftis/jackrabbit/blob/f5e538418e26482e18f3cd9f5f57bc0fa54e83cf/lib/exchange.js#L49

In this fork, we don't have that luxury.

https://github.com/pagerinc/jackrabbit/blob/master/lib/exchange.js#L64

**Comment by Akamaozu** [comment]
I could write a patch for this, but not sure why this was changed from the original fork.

Would like some clarity on this before trying to enable this via a patch.

**Comment by ryanhallcs** [comment]
@Akamaozu looks like the forks have split a good bit. This improvement was added after pagerinc forked, and was never pulled in. A patch would be wonderful

Side note that we (very) recently finished some long overdue cleanup, mostly around unit tests and formatting changes with properly linting in circleci, so expect some significant deltas
