### ISSUE TITLE
queue.consume now has a race condition in 4.8.0

### ISSUE THREAD

**Issue by Akamaozu** [pagerinc/jackrabbit#87]
Updated to 4.8.0 to test the new patch and noticed queue.consume was broken.

Kept getting this error message: "onMessage is not defined".

After going through the changes from 4.7.1 to 4.8.0, I think I discovered what the issue is.

4.7.1
https://github.com/pagerinc/jackrabbit/blob/f8dc44c9486ad6ee91cae342e06aea270c6b5540/lib/queue.js#L42-L55

4.8.0
https://github.com/pagerinc/jackrabbit/blob/d0aab9e3573e399f7909d63033cc59022bbc4097/lib/queue.js#L28-L42

In 4.7.1, `queue.consume`'s `onMessage` is a function.
In 4.8.0, `queue.consume`'s `onMessage` is a variable that later in the code gets an anonymous function assigned to it.

Seemingly no difference, but a very big one in practice.

If a connection has not yet been established, `queue.consume` will set up a listener for the connection event before trying to use `onMessage` in the consume function. This is most likely the path your code is taking.

If the connection has been established before `queue.consume` executes, then it immediately executes the consume logic using `onMessage`.

The problem in 4.8.0 is if the connection is already active, then it tries to consume before `onMessage` variable has been assigned the anonymous function. `onMessage` would be an empty variable and will throw an error.

You can experience this by delaying your queue.consume call with `setTimeout`.

**Comment by cilindrox** [comment]
Closed via #88
